spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yml
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 500MB
  session:
    timeout: 2D

server:
  tomcat:
    max-swallow-size: -1

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}